# Generated by Django 4.2.5 on 2023-10-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='Название модели')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='Название версии')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.model', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=5, verbose_name='Серийный номер')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.model', verbose_name='Модель')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.version', verbose_name='Версия')),
            ],
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('name', 'model'), name='unique model_version'),
        ),
    ]
